### PR TITLE
[WIP] Update project for swift 3

### PR DESCRIPTION
**Pull request by garnett**
This pull request is work in progress as it heavily depends on Quick and Nimble (it's not possible to run the tests at the [moment](https://github.com/Quick/Quick/issues/551))

PR itself includes 2 things:
1. Converts existing code using Xcode migrator
2 Adds some refinements according to Swift 3 guidelines (enum cases, some label arguments)

### CODE REVIEW

**Comment by yoichitgy** [comment]
Thanks @garnett for beginning the migration to Swift 3! We'll wait Quick and Nimble to merge your PR.

**Comment by garnett** [comment]
I'm going to keep it up to date ocasionally rebasing on master

**Comment by garnett** [comment]
@yoichitgy FYI just rebased the branch on current master.

**Comment by yoichitgy** [comment]
Thanks @garnett very much for rebasing it and fixing conflicts!

Yes, the Quick and Nimble people are great. I'll also try updating [Swinject/SwinjectStoryboard](https://github.com/Swinject/SwinjectStoryboard) to support Xcode 8 and Swift 3.

**Comment by yoichitgy** [comment]
@garnett, I sent a pull request, https://github.com/garnett/Swinject/pull/1, to your swift3 branch to fix Issue #120, which is code signing problem on Xcode 8. Would you merge the PR?

**Comment by garnett** [comment]
@yoichitgy of course, done!

**Comment by yoichitgy** [comment]
@garnett: I update the project for Xcode 8 beta 6. Unit tests run now (though some fail). Please merge [my swift3 branch](https://github.com/yoichitgy/Swinject/tree/swift3) when you update your swift3 branch. Thanks!

@nickleach7: I used your commits for Xcode 8 beta 6. I squashed them when I merged them. 049cfd2235cf273bc11ad1e0aba675f6512f4b59

**Comment by garnett** [comment]
@yoichitgy I'll do it later today 👍

**Comment by yoichitgy** [comment]
@garnett: I made a pull request for your simple merge.
https://github.com/garnett/Swinject/pull/2

**Comment by yoichitgy** [comment]
Thanks @garnett very much for your work to support Swift 3👍👍👍

I'm going to merge this pull request into master to avoid future merge conflicts with new feature implementation on master. We go with Swift 3 on master branch from now!

**Comment by yoichitgy** [comment]
By this pull request, Xcode 8 beta 6 is supported.

**Pull request merged**
