### PR TITLE
Update CI provider and fix Build Badge Address 

### PR DESCRIPTION
**Pull request by 1ucas**
This Pull Request updates the Build Badge to the new `Travis.com` CI Provider.
Which fixes issue #463 .

It also adds some GitHub Actions Workflows for:
- Testing the project
- Testing the package delivered on SPM
- Lint the PodSpec to be released on Cocoapods 

It's still a work in progress, while we verify everything is up and running correctly on Travis.

### CODE REVIEW

**Comment by 1ucas** [comment]
For it to be ready, I still need to:
- Check the current build history and status on Travis
- Fix the commentary on README
- Regenerate the project with XcodeGen to be sure we don't miss the test target config again

**Comment by 1ucas** [comment]
I disabled GitHub actions for now because we already have Travis running fine.

**Comment by yoichitgy** [comment]
Thank you for fixing the CI and unit tests on Linux too😃😃😃

**Review by yoichitgy — APPROVED** [review]
LGTM👍👍👍🚀🚀🚀

**Pull request merged**
