### PR TITLE
Change PersistentStorage to PermanentStorage

### PR DESCRIPTION
**Pull request by jkaan**
PersistentStorage does not exist at the moment. This refers to the
correct class for this object scope.

### CODE REVIEW

**Comment by yoichitgy** [comment]
Thanks for your PR👍 The doc is an example to create your own custom scope. `.graph` and `.container` scopes uses `PermanentStorage.init`.
https://github.com/Swinject/Swinject/blob/5c84eeffcf5590323258b65145a211361cc03346/Sources/ObjectScope.Standard.swift

To clarify the intention of the document, I think changing the part to `YourCustomStorage.init` looks better. What do you think about it?

**Comment by jkaan** [comment]
I do agree! However at that moment it would make sense to also add a little description on how to create a `YourCustomStorage.init`. Shall I extend this PR to also include a little bit of documentation on that? :)

**Comment by yoichitgy** [comment]
Sure👍 It's very helpful for Swinject users if you enhance the documentation👍👍👍

**Comment by jkaan** [comment]
@yoichitgy Could you take another look at this PR, please? I added a tiny bit of documentation on creating your own implementation of InstanceStorage.

**Comment by jakubvano** [comment]
IMO typical usage of custom object scope would use one of the default `InstanceStorage` implementations, that is why initial documentation didn't go into detail of explaining how to write `YourCustomStorage` (Your example is basically reimplementation of `PermanentStorage`).

I feel like use of custom `InstanceStorage` would have to be very specific and require quite detailed understanding of inner workings of `ObjectScope` system. Thus IMO it is not worth trying to cover it in the docs.

What do you think @jkaan ?

**Pull request closed without merging**
