### PR TITLE
Lazy injection

### PR DESCRIPTION
**Pull request by jakubvano**
My take on implementing the Lazy injection (#303). It definitely needs code cleaning, synchronicity considerations, and maybe some optimizations / api improvements.

Biggest change in the existing codebase is object graph caching, which is necessary to implement Lazy injection, as @J7mbo [pointed out](https://github.com/Swinject/Swinject/issues/303#issuecomment-370836649).

The idea is to generate an unique identifier for each graph resolution, and provide that information to  the`InstanceStorage` when retrieving / storing instances. Then `GraphStorage` is caching instances resolved in specific graphs, to return them if graph is restored. I'm keeping only weak references - this should be enough for purposes of graph caching, AFAICS has negligible memory impact and shouldn't lead to zombie instances.

### CODE REVIEW

**Comment by jakubvano** [comment]
While trying to make this feature more robust (e.g. properly work for registrations with arguments) I've converted to the solution, which basically makes lazy resolution implicit for all services with (AFAICS) minimal impact on performance:

There is a `InstanceWrapper` protocol, which is explicitly checked in the case when default resolution mechanism fails (i.e. there is no entry for `InstanceWrapper` type). When this happens, instance of the wrapper is created and transparently returned from `resolve` method.

As this additional resolution attempt is performed only when default mechanism fails, performance impacts on existing code should be minimal. 

And as a bonus, this `InstanceWrapper` concept should easily enable optional forwarding (much more efficiently then [this](#322) approach) - all one needs to do is:

```swift
extension Optional: InstanceWrapper {
    static var wrappedType: Any.Type { return Wrapped.self }
    
    init(inContainer container: Container, withInstanceFactory factory: @escaping () -> Any?) {
        self = factory() as? Wrapped
    }
}
```

**Comment by jakubvano** [comment]
I've been trying to make the `Lazy` feature thread safe, but it does not seem to be possible in the current model - i.e. i see no way of synchronizing instance resolution inside `Lazy.instance` getter.

**Comment by AnisovAleksey** [comment]
@jakubvano wow, your idea about `InstanceWrapper` is very good! 👍 
What problems still exist? (I mean why it is still WIP? :) )

**Comment by jakubvano** [comment]
Currently there are two areas in which I'm not completely sure how to proceed:

1. **Thread safety**  - as mentioned above, I see no way of making `InstanceWrapper`s thread safe - it would require redesign of thread safety model (#139). However, I'm leaning towards releasing the feature despite of that (e.g. `Assembler`s do not support thread safety yet #221).

2. **Provider circular dependency** - `Lazy` circular dependencies work as expected because of graph caching. However, this mechanism cannot be used for `Provider` dependencies, as it would result in always returning the same instance.
My dilemma here is whether we should make circular dependencies work with `Provider` as well, or is it something that user would not need - One example would be something like this:

```swift
class Controller: WorkDelegate {
    private let worker: Provider<Worker>
}

extension Controller: WorkerDelegate {
    func workCompleted() {  }
}

class Worker {
   weak var delegate: WorkerDelegate?
}
```
Here I might expect, that every provided worker would have have the same instance of `Controller` as delegate.

Would definitely appreciate any input on this :)

**Comment by jakubvano** [comment]
After further consideration, I came to the conclusion that expecting the `Provider` circular dependencies to work in `.graph` goes - in a way - against the main idea behind the `Provider`, would probably be useful only in very niche situations, and thus it is not worth to severly complicate the implementation of graph caching.

**Pull request merged**
