### PR TITLE
Enable multiple initCompleted definitions

### PR DESCRIPTION
**Pull request by AnisovAleksey**
Hi! check the pull request with implemented #324

### CODE REVIEW

**Comment by jakubvano** [comment]
Thanks for the PR! 👍 It looks very good (apart from minor codestyle violation 😉)

TravisCI build is currently failing on Linux - it seems that there is an issue with access to `private initCompletedActions`, but AFAICS it should work properly with swift4. I'll look into it.

**Comment by threat70** [comment]
@jakubvano I hope that now all will be ok :)

**Comment by threat70** [comment]
@jakubvano looks like one of simulators was crashed :( 
How I can restart all tests?

**Comment by jakubvano** [comment]
I've restarted the failed simulator, all is fine now 😄 
Thanks again for your contribution 👍

**Pull request merged**
