### PR TITLE
Change api for resolving with parameters

### PR DESCRIPTION
**Pull request by jakubvano**
Implements #63 - moves changes from #115 to `master` branch.

### CODE REVIEW

**Comment by yoichitgy** [comment]
Thank you @jakubvano for the great work to migrate the API with arguments😃😃😃

Also, thank you for being patient since you suggested the API change in February. I couldn't take much time, and it was really helpful that you implemented feature❗️

**Comment by yoichitgy** [comment]
I'll tag and release Swinject v2.0.0-beta1 in the next weekend.

**Comment by jakubvano** [comment]
Glad I could contribute :triumph: :smile:

**Comment by yoichitgy** [comment]
Released v2.0.0-beta.1❗️

https://github.com/Swinject/Swinject/releases/tag/2.0.0-beta.1

**Pull request merged**
