### PR TITLE
Remove Quick and Nimble submodules, and use pre-built frameworks instead

### PR DESCRIPTION
**Pull request by mpdifran**
Add Carthage/Checkout to .gitignore.
Update .travis.yml to run carthage bootstrap instead of git submodule update.
Copy Quick and Nimble frameworks into the test bundle.

### CODE REVIEW

**Comment by jakubvano** [comment]
Thanks for the PR 👍 
Looks like `carthage bootstrap` step is missing from `.travis.yml` config, so travis is unable to find linked frameworks.
Also, carthage frameworks need to be embeded in the test bundle, otherwise it fails with
>The bundle “SwinjectTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.

**Comment by mpdifran** [comment]
Ok, I'll add the `carthage bootstrap` step to `travis.yml`. I'll make sure they get embedded too.

**Comment by mpdifran** [comment]
Can we run the tests again?

**Comment by jakubvano** [comment]
I restarted the tests, but it they are failing in the linux environment - looks like `carthage bootstrap` should not be run there. For reference see [.travis.yml](https://github.com/Swinject/SwinjectAutoregistration/blob/migrate-to-prebuilt-frameworks/.travis.yml) in SwinjectAutoregistration, which [runs sucessfully](https://travis-ci.org/Swinject/SwinjectAutoregistration/builds/200658970) on linux env.

**Comment by mpdifran** [comment]
Looks like Linux is passing now. I think that one build just needs to be run again.

**Pull request merged**
