### PR TITLE
Removes codeCoverageEnabled=YES to solve Appstore Rejection issues

### PR DESCRIPTION
**Pull request by s4cha**
Removes codeCoverageEnabled=YES to solve Appstore Rejection issues 
explained here : https://github.com/Swinject/Swinject/issues/309

### CODE REVIEW

**Comment by jakubvano** [comment]
Thanks for the PR @s4cha ! Sorry for taking so long to get to it.

After reading [Resolving App Rejections for GCC and LLVM Instrumentation](https://developer.apple.com/library/content/qa/qa1964/_index.html) and [Carthage #2158](https://github.com/Carthage/Carthage/pull/2158) I believe that issue is not directly with Swinject settings (code coverage is useful during development), but rather with carthage using `build` instead of `archive` action to create framework.

This should be fixed in [Carthage 0.26](https://github.com/Carthage/Carthage/releases/tag/0.26.0). @BennX Would you mind checking if the latest Carthage verion resolves the issue?

**Comment by BennX** [comment]
@jakubvano right, it was an issue of carthage and seem to look fine now. 
Thanks for clarifying.

**Comment by jakubvano** [comment]
Thanks for the confirmation @BennX 👍 . Will close this PR, as it has become obsolete. Anyhow thanks @s4cha for the contribution 👍 😄

**Comment by s4cha** [comment]
@jakubvano @BennX Yep this was a dirty patch that is now obsolete.
Excuse the late reply :)

**Comment by yoichitgy** [comment]
Thanks @jakubvano for checking the Carthage issue!

**Pull request closed without merging**
