### PR TITLE
Project updates for Xcode 12

### PR DESCRIPTION
**Pull request by mpdifran**
Set minimum iOS version to 9.0.
Enable base localization.

### CODE REVIEW

**Comment by odanu** [comment]
What is missing  for going forward with this PR?

**Comment by mpdifran** [comment]
@odanu thats a Carthage issue with Xcode 12. There's a workaround in the related issue on the Carthage repo, I can paste the solution here when I'm back at my desk!

**Comment by odanu** [comment]
@mpdifran well, that's actually the issue. This error  appears after the  workaround is applied. But I already managed to dig deeper and found that it's not Swinject related. Cause after moving Swinject to SPM integration,  another dependency integrated using carthage failed with this error.

**Comment by mpdifran** [comment]
We're using Carthage to pull in Swinject on Xcode 12, I'd double check you've configured the workaround correctly!

**Comment by tkohout** [comment]
@mpdifran Xcode 12 shows `ambiguous use of expect` in `ContainerSpec` when running the tests. This code should fix it, can you include it in your PR?

```swift
let expectation: Expectation<Void> = expect {
    _ = parent.resolve(PetOwner.self)
}

expectation.notTo(throwAssertion())
```

**Comment by tkohout** [comment]
Thanks a lot @mpdifran

**Comment by tkohout** [comment]
@mpdifran Would you like to become a member of the Swinject team? You have probably done more work on the main repo than me.

**Comment by mpdifran** [comment]
@tkohout yeah I'd love to! I've been using it for the last four years so I have a huge vested interest in keeping it alive.

**Pull request merged**
