### PR TITLE
Customizable object scopes

### PR DESCRIPTION
**Pull request by jakubvano**
Relates to #80, #98, #106.

I've been thinking about parent-child container relationship, and realised that one of the difficulties of implementing e.g. `.hierarchy` scope, or some more complex object life time management is the fact that `Container` manages both service registrations and service instances.

So I thought to move responsibility of managing instance persistence to `ObjectScope`. It is currently only a draft, and would ofc require some more work. @yoichitgy What do you think? Could this be a way to go or is it too much of a breaking change?

Some implications of this paradigm:
- `ObjectScope.hierarchy` doesn't make sense, and `.singleton` is more fitting than `.container`
- parent container might be redundant, as scopes would (probably) be shared among all containers
- This enables custom scopes, e.g. if I had `SessionController` holding user-sensitive data which should be destroyed after logout, I could implement it like:

```
extension ObjectScope {
    static let user = ObjectScope(parent: .singleton, name: "user")
}

container.register(SessionController.self) { _ in SessionController() }
    .inObjectScope(.user)

func logout() {
    ...
    ObjectScope.user.discard()
}
```

### CODE REVIEW

**Comment by yoichitgy** [comment]
I'll reply shortly.

**Comment by yoichitgy** [comment]
Thanks for the great idea💡 Swinject v2 is still beta and it's a good opportunity to add breaking changes for great enhancements like you are thinking. The parent container and hierarchy scope made the implementation complicated, causing difficulty to add the other nice features.

It's nice to move the responsibility to ObjectScope because, as you said, it's extendable. It's also nice if experimental scopes can be added to another repository in Swinject organization, or third party repositories.

The `.user` scope is nice. I also wanted to add `.thread` or `.session` scopes for server-side use cases.

I chose the wording `.container` because Funq used the wording and Singleton pattern like `UIApplication.shared` is an anti pattern in DI, though the lifecycle of objects in `.singleton` scope is tied to their container. I wanted to avoid confusion for Swinject beginner users for the wording, though some other DI frameworks (including the other languages) name it singleton scope. By the way, `.none` is also a candidate to rename to clarify.

So, let's migrate to the better architecture you are writing in v2 beta. We can provide better scopes than `.hierarchy`.

**Comment by haitran2011** [comment]
ok

**Comment by jakubvano** [comment]
After several iterations I've finally come to an implementation of custom scopes I'm more-or-less satisfied with.

It provides `graph`, `none`, and `container` scopes, with easy addition of custom scopes, for example:

`user` scope:
```swift
extension ObjectScope {
    static let user = ObjectScope(storageFactory: PermanentStorage.init)
}
...
func logout() { container.resetObjectScope(.user) }
```

`weak` scope (#185):
```swift
extension ObjectScope {
    static let weak = ObjectScope(storageFactory: WeakStorage.init)
}
final class WeakStorage: InstanceStorage {
    class Wrapper {
        let value: Any
        init(_ value: Any) { self.value = value }
    }

    private weak var wrapper: Wrapper?
    var instance: Any? {
        get { return wrapper?.value }
        set { wrapper = newValue.map(Wrapper.init) }
    }
}
```
or `thread` scope:
```swift
extension ObjectScope {
    static let thread = ObjectScope(storageFactory: ThreadUniqueStorage.init)
}
final class ThreadUniqueStorage: InstanceStorage {
    var instances = [ObjectIdentifier: Any]()
    var instance: Any? {
        get { return instances[ObjectIdentifier(Thread.current)] }
        set { instances[ObjectIdentifier(Thread.current)] = newValue }
    }
}
```

Possible issue:
 -  I chose the`container` name as it has semantics of "instaces are persited for the entire lifetime of a container they are registered in", however this is in effect the same as old `.hierarchy` scope, so maybe it should be renamed.
- there is no equivalent of  old `container` scope, but IMO is not needed as container-based lifetime management of instances can be more easily expressed with custom scopes.
- I haven't changed the nature of parent-child relationship as I couldn't identify exact problems with current relationship, and removal of old `container` context IMO sufficiently reduces complexity.

**Comment by yoichitgy** [comment]
This feature removed the `switch` statement for scopes from `Container`, and its implementation was simplified. Using `ObjectScope` to create a `storage` lazily for a service entry is extensible and nice idea👍 Overall, I think it's great to migrate to the new scope model as Swinject v2.

- I think the concept of the old `.hierarchy` and `.container` scopes was complicated. When a parent-child relationship is created, taking the old `.hierarchy` scope (the new `.container` scope) is simple and makes sense.
- I think the scope name `.container` is ok because it is specified when a service is registered to a container. If the container has a child container, the child gets the instance stored in the parent container where `.container` scope is specified. It makes sense for me.
- If the old `.container` scope is really needed, it can be achieved by adding the same service registration to both parent and child containers. So, removing the old `.container` can be no problem. The advantage to get things much simpler is more important.
- `ObjectScope.none` looks good to be renamed to `.transient` as you named `TransientStorage` because `.none` doesn't make sense (though I named it in v1).

I have a nitpicking question.

- `resetObjectScope` of a container calls the method of its parent. Should it call the parent's? (I don't mean it shouldn't. I'm thinking which is more reasonable whether calling it or not.) What is the reason why the child call of `resetObjectScope` calls the parent one?

**Comment by jakubvano** [comment]
>ObjectScope.none looks good to be renamed to .transient as you named TransientStorage because .none doesn't make sense (though I named it in v1).

I agree, `.transient` is more descriptive.

>resetObjectScope of a container calls the method of its parent. Should it call the parent's? (I don't mean it shouldn't. I'm thinking which is more reasonable whether calling it or not.) What is the reason why the child call of resetObjectScope calls the parent one?

Main reason is `.graph` object scope, which needs to be reset after object graph is resolved. - if `resetObjectScope` did not reset parent, we would need different mechanism for `.graph` object scope, which would complicate implementation.
I can't come up with other arguments for either option, mostly because with custom scopes, I don't see reason for using more than one container - grouping can be achieved via `AssemblyType` and lifetime management via custom scopes. 
However, if you can see some scenarios in which not resetting the parent might be useful, I wouldn't mind changing the behaviour.

**Comment by yoichitgy** [comment]
Thank you for explaining the reason about `resetObjectScope`. I understood it😃 Let's move on with this implementation. (So far, I don't see any problems. I'll only ask you for some discussion if I find a problem for resetting parent's before we release Swinject v2 official version.)

As far as I heard, some people prefer using `AssemblyType` and some people prefer managing container groups by themselves with/without parent relationship. I think dropping parent relationship might be a too large breaking change.

**Comment by jakubvano** [comment]
I've renamed to `.transient` scope and updated documentation, so PR should be ready to merge.

I've also considered adding `.weak` object scope as discussed in #185, but it is probably better to do in separate PR.

**Comment by yoichitgy** [comment]
Swinject became not only more extendable but also simpler to maintain👍

**Comment by basalphenaar** [comment]
I couldn't help but check out the latest commit of Swinject to try this new feature, it can be really useful for the app I'm currently building (to manage user sessions). I'm also using SwinjectStoryboard and it doesn't seem to be working with that yet (I get a lot of segmentation fault errors when building my project). Did anybody get this running in combination with SwinjectStoryboard or is this not possible yet?

**Comment by jakubvano** [comment]
@basalphenaar currently it wont work with `SwinjectStoryboard`, because it has specified dependency on older `Swinject` release, thus two versions of Swinject framework being used (one in app one as dependency of `SwinjectStoryboard`) are not compatible.

**Comment by basalphenaar** [comment]
@jakubvano Thanks for your answer, indeed Carthage was also giving some conflict errors when using the latest commit of Swinject together with SwinjectStoryboard 1.0.0-beta2. No problem, I'll think of some other solution for now :)

**Pull request merged**
