### PR TITLE
Change syntax for resolving with arguments

### PR DESCRIPTION
**Pull request by jakubvano**
Implements #63

### CODE REVIEW

**Comment by yoichitgy** [comment]
@jakubvano, thank you very much for your great work to migrate the syntax, but unfortunately Swinject v1 series in `v1` branch keeps the previous syntax. Swinject v2 series in `master` branch will have the new syntax you implemented. Would you make a PR to `master` branch?

**Comment by yoichitgy** [comment]
@garnett, the syntax change will have conflict with #113 for Swift 3 support. Do you mind if I merge the syntax change to `master`?

**Comment by garnett** [comment]
@yoichitgy go ahead, there is no reason to stop developing in master while we wait swift3

**Comment by yoichitgy** [comment]
Thanks @garnett!

**Pull request closed without merging**
