### PR TITLE
Add support for DocC

### PR DESCRIPTION
**Pull request by mpdifran**
This is a draft with changes to better support Apple's new DocC format for documentation. More info [here](https://developer.apple.com/videos/play/wwdc2021/10166/?time=1050).

Might make sense to keep this branch out of master until Xcode 13 is closer to release.

- [x] Build DocC on every build of the framework
- [x] Update method doc formats to better take advantage of DocC

### CODE REVIEW

**Comment by mpdifran** [comment]
Let's get this in in its current form. We can always add more PRs for further DocC support. I'll create an issue to track progress here.

**Comment by mpdifran** [comment]
Create #477.

**Comment by mpdifran** [comment]
This is safe to go into master, as it doesn't break anything in Xcode 12.

**Comment by 1ucas** [comment]
DocC is the future of the documentation around the Apple environment. 
For me, it ok!
- [x] Tested on Xcode 12.5.1
- [x] Tested on Xcode 13.0b1
- [x] Verified after running gencode

**Review by 1ucas — APPROVED** [review]

**Pull request merged**
