### PR TITLE
Remove dependency on Quick/Nimble

### PR DESCRIPTION
**Pull request by yoichitgy**
This PR addresses issue #472.

- Replaced `XxxSpec` using Quick/Nimble with `XxxTests` using XCTest.
- Removed dependency on Quick/Nimble from Cartthage and SPM configs, and resulted in removal of dependency on Carthage.
- (This is not directly related to the issue) but fixed Xcode project setting to exclude SwiftLint.yml from Unit Test packages because those were included unnecessarily.

### CODE REVIEW

**Comment by 72A12F4E** [comment]
Hopefully this fixes my issues. I haven't been able to build locally & test on an iOS simulator because of  some issue with Quick & Nimble not setting up correctly when I `carthage bootstrap`

**Review by 72A12F4E — CHANGES_REQUESTED** [review]
One recommendation I would make is to enable code coverage for each scheme. When I checked out this PR locally, code coverage was disabled. 

I enabled it locally, and found that we're at about 72%.

**Comment by yoichitgy** [comment]
Thanks @72A12F4E for your comment! It's a nice idea to keep the code coverage visible to be aware to write unit tests👍 

It looked Swinject users saw some issues (#296 #309). Maybe it's nice to turn on code coverage measurement on CI or somewhere for contributors/maintainers💪

**Review by mpdifran — APPROVED** [review]

**Comment by mpdifran** [comment]
Tested resolving this branch via Carthage and SPM and everything works!

**Comment by yoichitgy** [comment]
Thank you for your kind and careful review😃 I merged the PR🚀

**Pull request merged**
