### PR TITLE
Fix deadlock when recursive resolving made on "thread safe" resolver

### PR DESCRIPTION
**Pull request by serges147**

### CODE REVIEW

**Comment by yoichitgy** [comment]
I think capturing the resolver returned from `container.synchronize()` in `register` closure is just misuse of SynchronizedResolver.

**Comment by serges147** [comment]
Could you please what foundamentially wrong with it? I agree that if you have `resolver` as first parameter of factory callback then you don't need to capture anything else - this as exctly as I did. Then I get wierd crash because of not being threadsafe with resolving, so I added the synchronize() - and guess what, even then you are not ok and Swinject wont help you. So capturing outside `threadSafeResolver` is kinda workaround, and IMO quite ligitimate one.

**Comment by yoichitgy** [comment]
I appreciate you tried to improve Swinject, but please check Issue #266😉

**Comment by jakubvano** [comment]
Original `it wont resolve the same instance` test was not valid use of swinject - not even `NSRecursiveLock` could enable that.
However, enabling nested resolves is possible by using `NSRecursiveLock` - I reimplemented that test in #351.

Thanks for your contribution 👍

**Comment by jakubvano** [comment]
Closing in favor of #353 & #350

**Pull request closed without merging**
