### PR TITLE
Added throws resolve

### PR DESCRIPTION
**Pull request by Lumyk**

### CODE REVIEW

**Comment by jakubvano** [comment]
Thanks for the PR! 👍 

What is the reasoning behind this functionality? Can you describe why it is necessary / beneficial? How would this change in API impact current users?

**Comment by Lumyk** [comment]
Added ability to make throws resolve

```swift
let container = Container()
container.register(Animal.self) { _ in Cat(name: "Mimi") }
container.register(Person.self) { r in
    PetOwner(pet: r.resolve(Animal.self)!)
}

do {
  let person = try container.throwsResolve(Person.self)
   person.play() // prints "I'm playing with Mimi."
} catch let error {
  // get error if not registered 'cantResolve(type:, name:)'
}

func init() throws {
  let person = try container.throwsResolve(Person.self)
}
```

You can guarantee not optional result or use ```try!``` and ```try?``` if needs

**Comment by jakubvano** [comment]
What are the usecase, in which it is beneficial to use `throwsResolve` instead of current `resolve`?

You could rewrite your examples with current API IMO without  loosing clarity.
```swift
guard let person = container.resolve(Person.self) else { 
    // do error handling
}
person.play()

func init() throws {
    guard let person = container.resolve(Person.self) else { throw SomeError() }
}
```
There has been some discussion about implementing throwable `resolve` in the past (see #99, [#6](https://github.com/Swinject/SwinjectAutoregistration/issues/6)), and at that time we came to the conclusion that changing the API is not wort it.

I wouldn't mind reopening this discussion - personally I would like throwing `resolve()` methods a bit more as well. 
However I don't think it is a good idea to have 2 kinds of API - if we wanted to have `throwsResolve`, it should probably replace current `resolve` API.

**Comment by Lumyk** [comment]
Think that ```throws``` better than ```Optional``` and more evidently in use. Hope you can find better solution to make all ```throws``` based. Ready to help if needs ;)

**Pull request closed without merging**
