### PR TITLE
Make synchronous reads and writes to the container safe

### LINKED ISSUE #539: Synchronous reads and writes fail
The documentation makes it clear that `Container` is not thread safe, but reads can be made thread safe by calling `.synchronize()` to get a `Resolver`. That is true if they are on their own. However, if you are writing to the container, the reads in the `Resolver`s are not necessarily thread safe.

This test demonstrates the issue:

```swift
    func testSynchronizedResolverHighCounts() {
        let container = Container()
        
        DispatchQueue.global(qos: .background).async {
            for index in 0...100_000 {
                container.register(Animal.self, factory: { _ in
                    Cat(name: "\(index)")
                })
            }
        }
        
        DispatchQueue.global(qos: .background).async {
            DispatchQueue.concurrentPerform(iterations: 100_000) { (index) in
                let cat = container.synchronize().resolve(Animal.self)
                print(String(describing: cat))
            }
        }
    }
```

Usually the test does pass. When it fails it's normally in the function `graphResolutionCompleted`, but I don't believe it's specific to that and could fail in other places.

### PR DESCRIPTION
**Pull request by dalemyers**
The `services` parameter is not thread safe. Concurrent reads are safe, but concurrent reads with writes happening at the same time are not. This adds a read/write lock around it, making reads synchronous and safe, but writes block to ensure safety.

Resolves #539

### CODE REVIEW

**Comment by Goles** [comment]
Seeing the same thing. Thanks for working on this.

**Comment by dalemyers** [comment]
@mpdifran / @maxim-chipeev Any chance of a review on this? Thanks! 😄

**Comment by dalemyers** [comment]
@mpdifran / @maxim-chipeev Just bumping this again as we are still seeing it and we'd really rather not have to fork.

**Review by maxim-chipeev — APPROVED** [review]
Thanks for the follow-up ping—and for adding the functionality, I will merge this in for the use-case of concurrent writes to the container.

**Pull request merged**
